#! /bin/sh
#
# trafficrcvd   Start/Stop trafficrcv.
#
# chkconfig: 2345 80 20
# description:  trafficrcv is a discard server.  It is used as a sink for \
#               traffic generated by the trafficsnd program as part of \
#               the PSC TCP testrig.
# processname: trafficrcv
# pidfile: /var/run/trafficrcv.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Get config to check for networking
. /etc/sysconfig/network

# Check that networking is up.
if [ ${NETWORKING} = "no" ]
then
        exit 0
fi

[ -f /usr/local/testrig/trafficrcv ] || exit 0

RETVAL=0

# See how we were called.
case "$1" in
  start)
        echo -n "Starting trafficrcv: "
        /usr/local/testrig/trafficrcv $2
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/trafficrcv
        ;;
  stop)
        echo -n "Stopping trafficrcv: "
        killproc trafficrcv
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/trafficrcv
        ;;
  status)
        status trafficrcv
        RETVAL=$?
        ;;
  *)
        echo "Usage: trafficrcv {start|stop|status} [socket buffer size in 
bytes]"
        exit 1
esac

exit $RETVAL
